// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCejiWOihNl7w-wT3ybEDNpATNkZFuOCH4',
    appId: '1:751272858210:web:9a14d6f53931eeec59373b',
    messagingSenderId: '751272858210',
    projectId: 'momentum-adfc0',
    authDomain: 'momentum-adfc0.firebaseapp.com',
    databaseURL: 'https://momentum-adfc0-default-rtdb.firebaseio.com',
    storageBucket: 'momentum-adfc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7l6rQgaXHh7KQlwp8ArHhuAVKbvFWcBY',
    appId: '1:751272858210:android:d7550e839bef59cc59373b',
    messagingSenderId: '751272858210',
    projectId: 'momentum-adfc0',
    databaseURL: 'https://momentum-adfc0-default-rtdb.firebaseio.com',
    storageBucket: 'momentum-adfc0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCejiWOihNl7w-wT3ybEDNpATNkZFuOCH4',
    appId: '1:751272858210:web:b99e828ed7a6ca9459373b',
    messagingSenderId: '751272858210',
    projectId: 'momentum-adfc0',
    authDomain: 'momentum-adfc0.firebaseapp.com',
    databaseURL: 'https://momentum-adfc0-default-rtdb.firebaseio.com',
    storageBucket: 'momentum-adfc0.firebasestorage.app',
  );
}
